version: 2
updates:
  - package-ecosystem: maven
    directory: /group-buying-market
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: maven
    directory: /group-buying-trade
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
